INSERT INTO tourism.categories (name) VALUES
                                  ('Automotive'),
                                  ('Business'),
                                  ('Culture'),
                                  ('Education'),
                                  ('Entertainment and Recreation'),
                                  ('Facilities'),
                                  ('Finance'),
                                  ('Food and Drink'),
                                  ('Geographical Areas'),
                                  ('Government'),
                                  ('Health and Wellness'),
                                  ('Housing'),
                                  ('Lodging'),
                                  ('Natural Features'),
                                  ('Places of Worship'),
                                  ('Services'),
                                  ('Shopping'),
                                  ('Sports'),
                                  ('Transportation');
